# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-10 07:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 10, 10, 7, 12, 49, 966767, tzinfo=utc))),
            ],
            options={
                'ordering': ('pub_date',),
            },
        ),
    ]
